name       : libwebkit-gtk
version    : 2.28.0
release    : 68
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.28.0.tar.xz : 361f3d178f62a9c112cbadfedd46106c34455c26d57a12a28fb3b09178d20e8b
homepage   : https://webkitgtk.org
license    : LGPL-2.1-only
component  : desktop.web
summary    : Web rendering engine
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
clang      : yes
optimize   :
    - no-symbolic
    - speed
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-gl-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libjpeg)
    - pkgconfig(libnotify)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libseccomp)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwebp)
    - pkgconfig(libwoff2dec)
    - pkgconfig(wpebackend-fdo-1.0)
    - pkgconfig(libxslt)
    - pkgconfig(ruby-2.6)
    - pkgconfig(sqlite3)
    - pkgconfig(xt)
    - bubblewrap
    - gperf
    - hyphen-devel
    - libgcrypt-devel
    - xdg-dbus-proxy
rundeps    :
    - bubblewrap
    - libwpe
    - wpebackend-fdo
    - xdg-dbus-proxy
setup      : |
    %cmake_ninja -DPORT=GTK
build      : |
    %ninja_build
install    : |
    %ninja_install
