name       : libwebkit-gtk
version    : 2.26.0
release    : 62
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.26.0.tar.xz : d210c0ecd1a89a22c9f8f1f450334f3489c5c50159b3a5e14dd93d5f349dcced
homepage   : https://webkitgtk.org
license    : LGPL-2.1-only
component  : desktop.web
summary    : Web rendering engine
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
clang      : yes
optimize   :
    - no-symbolic
    - speed
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-gl-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libjpeg)
    - pkgconfig(libnotify)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwebp)
    - pkgconfig(libwoff2dec)
    - pkgconfig(wpebackend-fdo-1.0)
    - pkgconfig(libxslt)
    - pkgconfig(ruby-2.6)
    - pkgconfig(sqlite3)
    - pkgconfig(xt)
    - gperf
    - hyphen-devel
    - libgcrypt-devel
rundeps    :
    - libwpe
    - wpebackend-fdo
setup      : |
    %cmake_ninja -DENABLE_BUBBLEWRAP_SANDBOX=false -DPORT=GTK
build      : |
    %ninja_build
install    : |
    %ninja_install
