name       : libwebkit-gtk
version    : 2.30.4
release    : 73
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.30.4.tar.xz : d595a37c5001ff787266b155e303a5f2e5b48a6d466f2714c2f30c11392f7b24
homepage   : https://webkitgtk.org
license    : LGPL-2.1-only
component  : desktop.web
summary    : Web rendering engine
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
clang      : yes
optimize   :
    - no-symbolic
    - speed
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gbm)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-gl-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libjpeg)
    - pkgconfig(libnotify)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libseccomp)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwebp)
    - pkgconfig(libwoff2dec)
    - pkgconfig(wpebackend-fdo-1.0)
    - pkgconfig(libxslt)
    - pkgconfig(ruby-2.7)
    - pkgconfig(sqlite3)
    - pkgconfig(xt)
    - bubblewrap
    - gperf
    - hyphen-devel
    - libgcrypt-devel
    - xdg-dbus-proxy
rundeps    :
    - bubblewrap
    - libwpe
    - wpebackend-fdo
    - xdg-dbus-proxy
setup      : |
    %cmake_ninja -DPORT=GTK
build      : |
    %ninja_build
install    : |
    %ninja_install
