name       : libwebkit-gtk
version    : 2.18.6
release    : 44
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.18.6.tar.xz : 93912cc2f40f12e452be1ca4babdbdaac0ec4f828d441257a6b06c2963bbac3c
homepage   : http://webkitgtk.org
license    : LGPL-2.1
component  : desktop.web
summary    : Web rendering engine
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-gl-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libjpeg)
    - pkgconfig(libnotify)
    - pkgconfig(libpng15)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwebp)
    - pkgconfig(libwoff2dec)
    - pkgconfig(libxslt)
    - pkgconfig(ruby-2.3)
    - pkgconfig(sqlite3)
    - pkgconfig(xt)
    - gperf
    - hyphen-devel
setup      : |
    %cmake_ninja -DPORT=GTK
build      : |
    %ninja_build
install    : |
    %ninja_install
