name       : libwebkit-gtk
version    : 2.20.3
release    : 52
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.20.3.tar.xz : 579b307d78fa16a73f112790178022166d7ad17d4147492ced9b9fba48f20dd8
homepage   : https://webkitgtk.org
license    : LGPL-2.1-only
optimize   :
    - no-symbolic
component  : desktop.web
summary    : Web rendering engine
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-gl-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libjpeg)
    - pkgconfig(libnotify)
    - pkgconfig(libpng)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwebp)
    - pkgconfig(libwoff2dec)
    - pkgconfig(libxslt)
    - pkgconfig(ruby-2.3)
    - pkgconfig(sqlite3)
    - pkgconfig(xt)
    - gperf
    - hyphen-devel
setup      : |
    %cmake_ninja -DPORT=GTK
build      : |
    %ninja_build
install    : |
    %ninja_install
