name       : libwebkit-gtk
version    : 2.16.2
release    : 30
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.16.2.tar.xz : 5ef689a202eb2b71141efbe8b7b53288adced90790f9f08df6e0a2ec1809f252
homepage   : http://webkitgtk.org
license    : LGPL-2.1
component  : desktop.web
summary    : Web rendering engine
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libnotify)
    - pkgconfig(libpng15)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwebp)
    - pkgconfig(libxslt)
    - pkgconfig(ruby-2.2)
    - pkgconfig(sqlite3)
    - pkgconfig(xt)
    - gperf
    - hyphen-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release -DPORT=GTK -DCMAKE_SKIP_RPATH=ON
build      : |
    %make
install    : |
    %make_install
