name       : libwebkit-gtk
version    : 2.26.2
release    : 66
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.26.2.tar.xz : 6b80f0637a80818559ac8fd50db3b394f41cb61904fb9b3ed65fa51635806512
homepage   : https://webkitgtk.org
license    : LGPL-2.1-only
component  : desktop.web
summary    : Web rendering engine
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
clang      : yes
optimize   :
    - no-symbolic
    - speed
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-gl-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libjpeg)
    - pkgconfig(libnotify)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libseccomp)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwebp)
    - pkgconfig(libwoff2dec)
    - pkgconfig(wpebackend-fdo-1.0)
    - pkgconfig(libxslt)
    - pkgconfig(ruby-2.6)
    - pkgconfig(sqlite3)
    - pkgconfig(xt)
    - bubblewrap
    - gperf
    - hyphen-devel
    - libgcrypt-devel
    - xdg-dbus-proxy
rundeps    :
    - bubblewrap
    - libwpe
    - wpebackend-fdo
    - xdg-dbus-proxy
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-build-with-icu-65.1.patch
    %cmake_ninja -DPORT=GTK
build      : |
    %ninja_build
install    : |
    %ninja_install
