name       : libwebkit-gtk
version    : 2.14.3
release    : 22
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.14.3.tar.xz : 0bead450a4c92024f09008725bb3e8c3830a32c7e2983d566368c4fede9e106c
homepage   : http://webkitgtk.org
license    :
    - LGPL-2.1
summary    : Web rendering engine
component  : desktop.web
builddeps  :
    - pkgconfig(libpng15)
    - pkgconfig(libwebp)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xt)
    - pkgconfig(gl)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libsecret-1)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(sqlite3)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(icu-uc)
    - pkgconfig(enchant)
    - pkgconfig(libnotify)
    - pkgconfig(gnutls)
    - pkgconfig(ruby-2.2)
    - gperf
    - libjpeg-turbo-devel
    - hyphen-devel
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release -DPORT=GTK -DCMAKE_SKIP_RPATH=ON
build      : |
    %make
install    : |
    %make_install
