name       : libwebkit-gtk
version    : 2.12.4
release    : 21
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.12.4.tar.xz : 424d3177599abbc1eb1a1ad7928dd280a62006e992f2fada2e059375a9609a77
homepage   : http://webkitgtk.org
license    :
    - LGPL-2.1
summary    : Web rendering engine
component  : desktop.web
builddeps  :
    - pkgconfig(libpng15)
    - pkgconfig(libwebp)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xt)
    - pkgconfig(gl)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libsecret-1)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(sqlite3)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(icu-uc)
    - pkgconfig(enchant)
    - pkgconfig(libnotify)
    - pkgconfig(gnutls)
    - pkgconfig(ruby-2.2)
    - gperf
    - libjpeg-turbo-devel
    - hyphen-devel
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release -DPORT=GTK -DCMAKE_SKIP_RPATH=ON
build      : |
    %make
install    : |
    %make_install
