name       : libwebkit-gtk
version    : 2.22.2
release    : 54
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.22.2.tar.xz : 345487d4d1896e711683f951d1e09387d3b90d7cf59295c0e634af7f515e99ba
homepage   : https://webkitgtk.org
license    : LGPL-2.1-only
optimize   :
    - no-symbolic
component  : desktop.web
summary    : Web rendering engine
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-gl-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libjpeg)
    - pkgconfig(libnotify)
    - pkgconfig(libpng)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwebp)
    - pkgconfig(libwoff2dec)
    - pkgconfig(libxslt)
    - pkgconfig(ruby-2.3)
    - pkgconfig(sqlite3)
    - pkgconfig(xt)
    - gperf
    - hyphen-devel
    - libgcrypt-devel
setup      : |
    %cmake_ninja -DPORT=GTK
build      : |
    %ninja_build
install    : |
    %ninja_install
