name       : libwebkit-gtk
version    : 2.40.4
release    : 98
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.40.4.tar.xz : 8d163379297a2f7f51b455127f99836d9fe1572289f77b630ff3d63a2cb06dac
homepage   : https://webkitgtk.org
license    : LGPL-2.1-only
component  : desktop.web
summary    : Web rendering engine
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
clang      : no # clang-14 issues
optimize   :
    - no-symbolic
    - speed
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gbm)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-gl-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gstreamer-transcoder-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(lcms2)
    - pkgconfig(libavif)
    - pkgconfig(libjpeg)
    - pkgconfig(libnotify)
    - pkgconfig(libopenjp2)
    - pkgconfig(libseccomp)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwebp)
    - pkgconfig(libwoff2dec)
    - pkgconfig(libxslt)
    - pkgconfig(ruby-3.2)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wpebackend-fdo-1.0)
    - pkgconfig(xt)
    - bubblewrap
    - gperf
    - hyphen-devel
    - libgcrypt-devel
    - unifdef
    - xdg-dbus-proxy
rundeps    :
    - bubblewrap
    - xdg-dbus-proxy
setup      : |
    %cmake_ninja -DENABLE_GAMEPAD=OFF -DPORT=GTK -DUSE_SOUP2=ON -DENABLE_DOCUMENTATION=OFF
build      : |
    %ninja_build -j6
install    : |
    %ninja_install

    # resolve conflicts with libwebkit-gtk41
    rm -fr $installdir/usr/bin
