name       : libwebkit-gtk
version    : 2.14.4
release    : 24
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.14.4.tar.xz : d1ae2df51dd4ee44b9b89421a436ef71062816308738c3712ecf4bec3ccbe3ac
homepage   : http://webkitgtk.org
license    :
    - LGPL-2.1
summary    : Web rendering engine
component  : desktop.web
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libnotify)
    - pkgconfig(libpng15)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwebp)
    - pkgconfig(libxslt)
    - pkgconfig(ruby-2.2)
    - pkgconfig(sqlite3)
    - pkgconfig(xt)
    - gperf
    - hyphen-devel
    - libjpeg-turbo-devel
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release -DPORT=GTK -DCMAKE_SKIP_RPATH=ON
build      : |
    %make
install    : |
    %make_install
