name       : libwebkit-gtk
version    : 2.34.3
release    : 83
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.34.3.tar.xz : 0d2f37aa32e21a36e4dd5a5ce7ae5ce27435c29d6803b962b8c90cb0cc49c52d
homepage   : https://webkitgtk.org
license    : LGPL-2.1-only
component  : desktop.web
summary    : Web rendering engine
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
clang      : yes
optimize   :
    - no-symbolic
    - speed
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gbm)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-gl-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(libnotify)
    - pkgconfig(libopenjp2)
    - pkgconfig(libseccomp)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwebp)
    - pkgconfig(libwoff2dec)
    - pkgconfig(libxslt)
    - pkgconfig(ruby-3.0)
    - pkgconfig(wpebackend-fdo-1.0)
    - pkgconfig(xt)
    - bubblewrap
    - gperf
    - hyphen-devel
    - libgcrypt-devel
    - xdg-dbus-proxy
rundeps    :
    - bubblewrap
    - xdg-dbus-proxy
setup      : |
    %cmake_ninja -DENABLE_GAMEPAD=OFF -DPORT=GTK -DUSE_SOUP2=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
