name       : libwebkit-gtk
version    : 2.16.1
release    : 29
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.16.1.tar.xz : eb92383232328ce655b703c64370ed3795662479719ad1b4a869ed46769d2945
homepage   : http://webkitgtk.org
license    : LGPL-2.1
summary    : Web rendering engine
component  : desktop.web
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gl)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(libnotify)
    - pkgconfig(libpng15)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwebp)
    - pkgconfig(libxslt)
    - pkgconfig(ruby-2.2)
    - pkgconfig(sqlite3)
    - pkgconfig(xt)
    - gperf
    - hyphen-devel
    - libjpeg-turbo-devel
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
setup      : |
    %patch -p1 < $pkgfiles/0001-Resolve-issues-with-inability-to-signin-with-Google.patch
    %cmake -DCMAKE_BUILD_TYPE=Release -DPORT=GTK -DCMAKE_SKIP_RPATH=ON
build      : |
    %make
install    : |
    %make_install
